#+TITLE: JIRA API v3 Backend for Org Export Engine
#+AUTHOR: Wolfgang Mederle
#+Startup: indent


* Introduction

This module plugs into the regular Org Export Engine and transforms Org files to JIRA markup for pasting into Jira tickets & comments.

It is also required for ejira3 to export tickets from Org do Jira.

The code is forked from Stig Brautaset's ox-jira and adapted to work with Jira API version 3. This version of the API replaces Jira markup with Atlassian Document Format, a JSON format described [[https://developer.atlassian.com/cloud/jira/platform/apis/document/structure/][here]].

I am working with the module daily, but consider it alpha. Not everything is implemented yet. What should work:

- text
- styled text (bold, italic, strikethrough, underline)
- code blocks
- verbatim and example blocks
- links
- mentions (via e. g. ejira3-mention-user, mentions require the person's ID)
- plain lists (numbered are converted to plain), also nested
- tables
  
* Usage

  In an Org buffer, hit =C-c C-e J j= to bring up =*Org Export Dispatcher*=
  and export it as a JIRA buffer. You can then use =C-x h= to mark the whole
  buffer, then =M-w= to save it to the kill ring (and global pasteboard) for
  pasting into JIRA issues.

  (ox-jira used =C-c C-e j j=, but this is also used in ox-json.)

  Alternatively, you can export to the kill ring automatically for
  interactive exports by setting this in your =.emacs.el= file:

  #+BEGIN_SRC emacs-lisp
    (setq org-export-copy-to-kill-ring 'if-interactive)
  #+END_SRC

* Installation

  This library is not on Melpa. For now, you need to install it manually.

* Manual installation

  Since you cannot install it from Melpa, simply clone this repo and do:

  #+BEGIN_EXAMPLE
  M-x load-file RET ox-jira3.el RET
  #+END_EXAMPLE

* Maturity

  It works as exporter for ejira3, that's my main use case. 

* License

  Copyright (C) 2025 Wolfgang Mederle

  This program is free software: you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by the Free
  Software Foundation, either version 3 of the License, or (at your option)
  any later version.

  This program is distributed in the hope that it will be useful, but WITHOUT
  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
  more details.

  You should have received a copy of the GNU General Public License along with
  this program. If not, see <http://www.gnu.org/licenses/>.

* Contributing

  I'm happy to consider contributions. Since this is my first attempt at an
  Emacs package I've bound to have made lots of mistakes. Help me correct
  them, and keep the pull requests coming!

  I am more likely to merge code contributions if they come with tests.
  However, code contributions are not everything. Opening an issue with a
  reproducible test case, like "I expected this but got this" is also a
  valuable contribution.

  ^ I borrowed this from ox-jira, and it is a bit hypocritical in case
  of ox-jira3, because the tests currently don't work at all; they are
  left over from ox-jira, which creates Jira markup.
