version: 2.1

jobs:
  test:
    parameters:
      emacs-version:
        type: integer
    docker:
      - image: silex/emacs:<< parameters.emacs-version >>-ci
    steps:
      - checkout
      - run: ./run-tests.sh

workflows:
  integrate:
    jobs:
      - test:
          matrix:
            parameters:
              emacs-version:
                - 27
                - 28
                - 29
